# version: '3.8'

# services:
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: api_service
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#     depends_on:
#       - db

#   db:
#     image: ankane/pgvector
#     container_name: pgvector_demo
#     environment:
#       POSTGRES_PASSWORD: pass123
#     ports:
#       - "5432:5432"

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy  # Ensures the database is ready
    environment:
      DBNAME: vector_db
      DBUSER: postgres
      DBPASSWORD: pass123
      DBHOST: db
      DBPORT: 5432

  db:
    image: ankane/pgvector
    container_name: pgvector_demo
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: postgres
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
